spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.131:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.199.131
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.199.131
    port: 6379
  zipkin:
    base-url: http://192.168.199.131:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
env:
  test13
girl:
  name: mo
  age: 17
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
