spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.183:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.199.131
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.199.131
    port: 6379
  jpa:
    show-sql: true
girl: 18
