spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://192.168.43.167:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.43.167
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.43.167
    port: 6379
  jpa:
    show-sql: true
girl: 18
